"use client";

import type { NewsItem, StockAnalysis, MacroImpact, NewsTrade } from "@/lib/types";

interface Props {
  news: NewsItem[];
  sentiment: {
    sentiment: string;
    bullish: number;
    bearish: number;
    neutral: number;
    total: number;
  };
  macroEvents: MacroImpact[];
  stocks: StockAnalysis[];
  newsTrades?: NewsTrade[];
}

export default function NewsAlerts({ news, sentiment, macroEvents, stocks, newsTrades = [] }: Props) {
  const bullishNews = news.filter((n) => n.sentiment === "BULLISH");
  const bearishNews = news.filter((n) => n.sentiment === "BEARISH");
  const neutralNews = news.filter((n) => n.sentiment === "NEUTRAL");

  const getAffectedStocks = (headline: string) => {
    const words = headline.toUpperCase().split(/\s+/);
    return stocks.filter((s) => {
      const name = s.name.toUpperCase();
      const sym = s.symbol.replace(".NS", "").toUpperCase();
      return words.some((w) => w.length > 3 && (name.includes(w) || sym.includes(w)));
    });
  };

  return (
    <div className="space-y-6">
      <h2 className="text-xl font-black">News & Alerts Dashboard</h2>

      {/* NEWS-DRIVEN TRADE SUGGESTIONS — the key new feature */}
      {newsTrades.length > 0 && (
        <div className="bg-accent/5 rounded-xl border-2 border-accent/30 p-4">
          <h3 className="text-sm font-black text-accent uppercase tracking-wider mb-3">
            News-Driven Trade Suggestions ({newsTrades.length})
          </h3>
          <p className="text-[10px] text-muted mb-3">
            These trades are generated by combining news sentiment + technical indicator scores. News confirms the indicator direction.
          </p>
          <div className="space-y-3">
            {newsTrades.map((t, i) => {
              const isBuy = t.action === "BUY";
              return (
                <div key={i} className={`rounded-xl border-2 p-4 ${isBuy ? "border-green/30 bg-green/5" : "border-red/30 bg-red/5"}`}>
                  <div className="flex items-center justify-between mb-2">
                    <div className="flex items-center gap-3">
                      <span className={`text-xs font-black px-3 py-1 rounded-lg ${isBuy ? "bg-green text-white" : "bg-red text-white"}`}>
                        {t.action}
                      </span>
                      <span className="font-bold text-lg">{t.name}</span>
                      <span className="text-xs text-muted">{t.symbol.replace(".NS", "")}</span>
                      <span className="text-[10px] bg-card px-2 py-0.5 rounded text-muted">{t.trade_type}</span>
                    </div>
                    <div className="flex items-center gap-4 text-xs">
                      <div className="text-center">
                        <div className="text-muted">Entry</div>
                        <div className="font-bold">₹{t.price?.toLocaleString("en-IN")}</div>
                      </div>
                      <div className="text-center">
                        <div className="text-muted">SL</div>
                        <div className="font-bold text-red">₹{t.stop_loss?.toLocaleString("en-IN")}</div>
                      </div>
                      <div className="text-center">
                        <div className="text-muted">Target</div>
                        <div className="font-bold text-green">₹{t.target_1?.toLocaleString("en-IN")}</div>
                      </div>
                      <div className={`px-3 py-1 rounded-lg text-center ${
                        t.confidence >= 7 ? "bg-green/20 text-green" : t.confidence >= 5 ? "bg-yellow/20 text-yellow" : "bg-red/20 text-red"
                      }`}>
                        <div className="text-[9px] font-bold">CONF</div>
                        <div className="font-black text-lg">{t.confidence}/10</div>
                      </div>
                    </div>
                  </div>

                  {/* Why this trade */}
                  <div className="bg-background rounded-lg p-3 mb-2">
                    <div className="text-[10px] font-bold text-accent uppercase mb-1">WHY</div>
                    <p className="text-xs text-foreground/80">{t.reason}</p>
                  </div>

                  {/* The news driving it */}
                  <div className="bg-background rounded-lg p-3">
                    <div className="text-[10px] font-bold text-yellow uppercase mb-1">NEWS TRIGGER</div>
                    <p className="text-xs text-foreground/80">{t.news_headline}</p>
                    <div className="flex items-center gap-2 mt-1">
                      <span className={`text-[9px] font-bold px-1.5 py-0.5 rounded ${
                        t.news_sentiment === "BULLISH" ? "bg-green/10 text-green" : "bg-red/10 text-red"
                      }`}>
                        {t.news_sentiment}
                      </span>
                      <span className="text-[9px] text-muted">
                        Indicator Score: {t.indicator_score > 0 ? "+" : ""}{t.indicator_score}
                      </span>
                      {t.sectors?.map((s) => (
                        <span key={s} className="text-[9px] bg-accent/10 text-accent px-1.5 py-0.5 rounded">{s}</span>
                      ))}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Sentiment Overview */}
      <div className="bg-card rounded-xl border border-border p-4">
        <div className="flex items-center gap-4 mb-3">
          <h3 className="text-sm font-bold">Market Sentiment</h3>
          <span className={`text-xs font-bold px-3 py-1 rounded-full ${
            sentiment.sentiment === "BULLISH" ? "bg-green/10 text-green" :
            sentiment.sentiment === "BEARISH" ? "bg-red/10 text-red" :
            "bg-yellow/10 text-yellow"
          }`}>
            {sentiment.sentiment}
          </span>
        </div>
        <div className="flex h-6 rounded-full overflow-hidden bg-background mb-2">
          {sentiment.bullish > 0 && (
            <div className="bg-green flex items-center justify-center text-[9px] text-white font-bold"
              style={{ width: `${(sentiment.bullish / Math.max(sentiment.total, 1)) * 100}%` }}>
              {sentiment.bullish}
            </div>
          )}
          {sentiment.neutral > 0 && (
            <div className="bg-yellow flex items-center justify-center text-[9px] text-black font-bold"
              style={{ width: `${(sentiment.neutral / Math.max(sentiment.total, 1)) * 100}%` }}>
              {sentiment.neutral}
            </div>
          )}
          {sentiment.bearish > 0 && (
            <div className="bg-red flex items-center justify-center text-[9px] text-white font-bold"
              style={{ width: `${(sentiment.bearish / Math.max(sentiment.total, 1)) * 100}%` }}>
              {sentiment.bearish}
            </div>
          )}
        </div>
      </div>

      {/* Macro Events */}
      {macroEvents.length > 0 && (
        <div className="bg-card rounded-xl border border-border p-4">
          <h3 className="text-sm font-bold mb-3">Macro Impact Events</h3>
          <div className="space-y-2">
            {macroEvents.map((e, i) => (
              <div key={i} className={`rounded-lg p-3 border ${
                e.severity === "HIGH" ? "bg-red/5 border-red/20" :
                e.severity === "MEDIUM" ? "bg-yellow/5 border-yellow/20" :
                "bg-card border-border"
              }`}>
                <div className="flex items-center gap-2 mb-1">
                  <span className={`text-[10px] font-bold px-2 py-0.5 rounded ${
                    e.severity === "HIGH" ? "bg-red/10 text-red" :
                    e.severity === "MEDIUM" ? "bg-yellow/10 text-yellow" : "bg-muted/10 text-muted"
                  }`}>{e.severity}</span>
                  <span className="text-sm font-bold">{e.event}</span>
                </div>
                <p className="text-xs text-muted">{e.impact}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* News by Sentiment */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        {/* Bullish */}
        <div className="bg-green/5 rounded-xl border border-green/20 p-4">
          <h3 className="text-sm font-bold text-green mb-3">BULLISH NEWS ({bullishNews.length})</h3>
          <div className="space-y-2 max-h-96 overflow-y-auto">
            {bullishNews.length === 0 ? <p className="text-xs text-muted">No bullish news</p> :
              bullishNews.map((n, i) => {
                const affected = getAffectedStocks(n.headline);
                return (
                  <div key={i} className="bg-card rounded-lg p-3 border border-border">
                    <p className="text-xs text-foreground leading-snug mb-1">
                      {n.url ? <a href={n.url} target="_blank" rel="noopener noreferrer" className="hover:text-green">{n.headline}</a> : n.headline}
                    </p>
                    <div className="flex items-center justify-between flex-wrap gap-1">
                      <span className="text-[9px] text-muted">{n.source}</span>
                      {affected.length > 0 && (
                        <div className="flex gap-1 flex-wrap">
                          {affected.slice(0, 3).map((s) => (
                            <span key={s.symbol} className={`text-[9px] px-1.5 py-0.5 rounded font-bold ${
                              s.signal === "BUY" || s.signal === "STRONG_BUY"
                                ? "bg-green/20 text-green" : "bg-muted/20 text-muted"
                            }`}>
                              {s.name} {s.score > 0 ? `+${s.score}` : s.score}
                            </span>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>
                );
              })
            }
          </div>
        </div>

        {/* Bearish */}
        <div className="bg-red/5 rounded-xl border border-red/20 p-4">
          <h3 className="text-sm font-bold text-red mb-3">BEARISH NEWS ({bearishNews.length})</h3>
          <div className="space-y-2 max-h-96 overflow-y-auto">
            {bearishNews.length === 0 ? <p className="text-xs text-muted">No bearish news</p> :
              bearishNews.map((n, i) => {
                const affected = getAffectedStocks(n.headline);
                return (
                  <div key={i} className="bg-card rounded-lg p-3 border border-border">
                    <p className="text-xs text-foreground leading-snug mb-1">
                      {n.url ? <a href={n.url} target="_blank" rel="noopener noreferrer" className="hover:text-red">{n.headline}</a> : n.headline}
                    </p>
                    <div className="flex items-center justify-between flex-wrap gap-1">
                      <span className="text-[9px] text-muted">{n.source}</span>
                      {affected.length > 0 && (
                        <div className="flex gap-1 flex-wrap">
                          {affected.slice(0, 3).map((s) => (
                            <span key={s.symbol} className={`text-[9px] px-1.5 py-0.5 rounded font-bold ${
                              s.signal === "SELL" || s.signal === "STRONG_SELL"
                                ? "bg-red/20 text-red" : "bg-muted/20 text-muted"
                            }`}>
                              {s.name} {s.score > 0 ? `+${s.score}` : s.score}
                            </span>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>
                );
              })
            }
          </div>
        </div>

        {/* Neutral */}
        <div className="bg-yellow/5 rounded-xl border border-yellow/20 p-4">
          <h3 className="text-sm font-bold text-yellow mb-3">NEUTRAL NEWS ({neutralNews.length})</h3>
          <div className="space-y-2 max-h-96 overflow-y-auto">
            {neutralNews.length === 0 ? <p className="text-xs text-muted">No neutral news</p> :
              neutralNews.map((n, i) => (
                <div key={i} className="bg-card rounded-lg p-3 border border-border">
                  <p className="text-xs text-foreground leading-snug mb-1">
                    {n.url ? <a href={n.url} target="_blank" rel="noopener noreferrer" className="hover:text-yellow">{n.headline}</a> : n.headline}
                  </p>
                  <span className="text-[9px] text-muted">{n.source}</span>
                </div>
              ))
            }
          </div>
        </div>
      </div>
    </div>
  );
}
